# Generated by Django 3.2.5 on 2021-07-30 09:04

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
