# Generated by Django 3.2.5 on 2021-07-30 11:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usermodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
