# Generated by Django 3.2.5 on 2021-07-30 11:30

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_usermodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover', validators=[main.validators.image_dimensions]),
        ),
    ]
